### ISSUE TITLE
Some question about negatives

### ISSUE THREAD

**Issue by whu-lyh** [PRBonn/kppr#3]
Hi, after trying your code, I found some questions that quite confuse me. 
1) At the momentum contrast mode, the positives and negative sample are actually from query data in a PR task. Am I right? 
2) On common triplet-based method, the anchor data, also named as query is from query dataset, while the positive and negative data are both from database dataset.

Thanks for your reply!

**Comment by louis-wiesmann** [comment]
@whu-lyh I'm not completly sure if this answers your question but let me try: 

1. For the training there is only one database (or dataset) with point clouds from different places at different points in time. 
2. For the triplet loss we take a random point cloud as query from the dataset and process it with our query model. 
3. Then we take a random positive match from the database (that is within 25m and from a different time) but process it with the key model
4. The negative is also from that dataset but instead of computing the descriptor we take it from the feature bank. The feature bank is just a rolling buffer that gets filled with the descriptors from the positives.

**Comment by whu-lyh** [comment]
Thanks, I get you.
